import Timeline from "@/components/timeline";
import Head from "next/head";

function Home() {
  return (
    <>
      <Head>
        <title>T3 Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Timeline />
    </>
  );
}

export default Home;
